# Generated by Django 5.2 on 2025-04-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soildata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('ph', models.FloatField()),
                ('texture', models.CharField(max_length=50)),
            ],
        ),
    ]
