# Generated by Django 5.2 on 2025-04-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_soildata'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='humidity',
            field=models.FloatField(default=0),
        ),
    ]
